package generator

// Templates for docker-compose generation
// These can be expanded with Go templates if needed

const composeHeader = `# AUTO-GENERATED by grund - DO NOT EDIT
version: "3.8"

networks:
  grund:
    driver: bridge

volumes:
`

// Additional template functions can be added here for more complex generation
